openapi: 3.0.0
info:
  title: HL7v2 to FHIR Custom Mapping Service
  version: 1.0.0
  description: API for customizingHL7v2 segments to FHIR mappings.
servers:
  - url: http://localhost:9091/v2tofhir
paths:
  /segment/nk1:
    post:
      summary: Handle NK1 segment
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
        '500':
          description: Internal Server Error
  /segment/pid:
    post:
      summary: Handle PID segment
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
        '500':
          description: Internal Server Error
  /segment/pd1:
    post:
      summary: Handle PD1 segment
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
        '500':
          description: Internal Server Error
  /segment/pv1:
    post:
      summary: Handle PV1 segment
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
        '500':
          description: Internal Server Error
  /segment/dg1:
    post:
      summary: Handle DG1 segment
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
        '500':
          description: Internal Server Error
  /segment/al1:
    post:
      summary: Handle AL1 segment
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
        '500':
          description: Internal Server Error
  /segment/evn:
    post:
      summary: Handle EVN segment
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
        '500':
          description: Internal Server Error
  /segment/msh:
    post:
      summary: Handle MSH segment
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
        '500':
          description: Internal Server Error
  /segment/pv2:
    post:
      summary: Handle PV2 segment
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
        '500':
          description: Internal Server Error
  /segment/obx:
    post:
      summary: Handle OBX segment
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
        '500':
          description: Internal Server Error
  /segment/orc:
    post:
      summary: Handle ORC segment
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
        '500':
          description: Internal Server Error
  /segment/obr:
    post:
      summary: Handle OBR segment
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
        '500':
          description: Internal Server Error
  /segment/nte:
    post:
      summary: Handle NTE segment
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
        '500':
          description: Internal Server Error
  /segment/sft:
    post:
      summary: Handle SFT segment
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
        '500':
          description: Internal Server Error
  /segment/iam:
    post:
      summary: Handle IAM segment
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
        '500':
          description: Internal Server Error
  /segment/mrg: 
    post:
      summary: Handle MRG segment
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
        '500':
          description: Internal Server Error
  /segment/tq1:
    post:
      summary: Handle TQ1 segment
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
        '500':
          description: Internal Server Error
  /segment/rxa: 
    post:
      summary: Handle RXA segment
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
        '500':
          description: Internal Server Error
  /segment/rxo:
    post:
      summary: Handle RXO segment
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
        '500':
          description: Internal Server Error
  /segment/rxr:
    post:
      summary: Handle RXR segment
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
        '500':
          description: Internal Server Error                                                     
  /segment/in1:
    post:
      summary: Handle IN1 segment
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
        '500':
          description: Internal Server Error
  /segment/in3: 
    post:
      summary: Handle IN3 segment
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
        '500':
          description: Internal Server Error                
  /segment/pr1:
    post:
      summary: Handle PR1 segment
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
        '500':
          description: Internal Server Error
  /segment/prt:
    post:
      summary: Handle PRT segment
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
        '500':
          description: Internal Server Error
  /segment/spm:
    post:
      summary: Handle SPM segment
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
        '500':
          description: Internal Server Error
  /segment/txa:
    post:
      summary: Handle TXA segment
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
        '500':
          description: Internal Server Error
  /segment/aig:
    post:
      summary: Handle AIG segment
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
        '500':
          description: Internal Server Error
  /segment/ail:
    post:
      summary: Handle AIL segment
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
        '500':
          description: Internal Server Error
  /segment/aip:
    post:
      summary: Handle AIP segment
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
        '500':
          description: Internal Server Error
  /segment/ais: 
    post:
      summary: Handle AIS segment
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
        '500':
          description: Internal Server Error
  /segment/sch:
    post:
      summary: Handle SCH segment
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
        '500':
          description: Internal Server Error
  /segment/rol:
    post:
      summary: Handle ROL segment
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
        '500':
          description: Internal Server Error                                                                                