[package]
org = "wso2"
name = "FHIRPathService"
authors = ["Ballerina"]
keywords = ["Healthcare", "FHIR", "FHIRPATH"]
version = "1.0.1"
distribution = "2201.10.2"

[build-options]
observabilityIncluded = true
